hash-format = "sha256"

[[files]]
file = "config/fancymenu/assets/Miniview.png"
hash = "26f0da5866839d6f175f77eeebffbfce3b94ba5eafd4c125c688c45a91178f64"

[[files]]
file = "config/fancymenu/assets/window-icon/16.png"
hash = "ffa9c1b2c20feda6f03f9dcc3d615907a751df90b76dd93f015169c3c316cc77"

[[files]]
file = "config/fancymenu/assets/window-icon/32.png"
hash = "fd72892bebfdc21ed796ecd1142915fc4b67d2ce458d508b94fd5f1a4e14c1a7"

[[files]]
file = "config/fancymenu/assets/window-icon/mac.icns"
hash = "9771894b8092e4434a82c4f8f37aa98ea865eb45a707d20d7bc5c73bca3e626a"

[[files]]
file = "config/fancymenu/custom_gui_screens.txt"
hash = "ff492043eaf454c46e949d5eef32ece90cc5a19feb50a161dd29a43b5732c880"

[[files]]
file = "config/fancymenu/customizablemenus.txt"
hash = "9bfce8b2f2241a394a05b2a9395983bf68d56ca19ad94ec5175423d39215045d"

[[files]]
file = "config/fancymenu/customization/connect_screen_layout.txt"
hash = "14165f90334807d5234644b98510ebf784bc2697176bd8ab77a3b264076c96d4"

[[files]]
file = "config/fancymenu/customization/drippy_loading_overlay_layout.txt"
hash = "6dc73db610f8f2dfe4553be62b759e212743053fd424a7ae3d5bcd6e87288e0c"

[[files]]
file = "config/fancymenu/customization/pause_screen_layout.txt"
hash = "7779be0960bd301f396cba05ad8cb037d43305b0b9321478087891011f5a4d74"

[[files]]
file = "config/fancymenu/customization/title_screen_layout.txt"
hash = "c7668213362bef74b011eb0fe6b7e544995b36b2fa70f5848c1c1890c411e7b0"

[[files]]
file = "config/fancymenu/layout_editor/widgets/element_layer_control.lewidget"
hash = "e2bc51781333e5af405b2a76fba8f1f0d7e83589c63502dc24cad0a0ef194424"

[[files]]
file = "config/fancymenu/legacy_checklist.txt"
hash = "9a25d3dc708e43eabafce5479a13c02dae15bc7f673afb2745b8b2ba48a97dc0"

[[files]]
file = "config/fancymenu/options.txt"
hash = "68820cf6cfbd70ab982b11189973b435ba4ae6fe47b795434eb8dcfcfe368489"

[[files]]
file = "config/fancymenu/ui_themes/dark.json"
hash = "45541e5c5019585b9c4ff114aed530826129e8a7ac6866b5d5fe41dd278abae4"

[[files]]
file = "config/fancymenu/ui_themes/light.json"
hash = "6954379d658fdf496f162792a3244f0f08635858ed4b0553a718a7ef63b8a620"

[[files]]
file = "config/fancymenu/user_variables.db"
hash = "3d7d4cda73d6bde134a568ccbe4e8d2e7fbe701570012b71fa45acdb2258c823"

[[files]]
file = "mods/AI-Improvements-1.21-0.5.3.jar"
hash = "795618769ff1ac782750be9e8faaf3e3d212f1687c3baab98c1282a98a63a41e"

[[files]]
file = "mods/AdvancedBackups-neoforge-1.21-3.7.1.jar"
hash = "50a3699f05952035bbbd2b5f3e9e11fcc43bfc9d5fee8c104b4ed7b32ef496be"

[[files]]
file = "mods/Chunky-NeoForge-1.4.23.fALzjamp.jar"
hash = "d72f235cf1f56f2c374f52c00bdda5034524b28142305a84cfc123a3f92ad274"

[[files]]
file = "mods/Clumps-neoforge-1.21.1-19.0.0.1.Wnxd13zP.jar"
hash = "b524ccdace2ef8fd19f5b2074f7de1103ac5065c52553f064c00e098346c293e"

[[files]]
file = "mods/CraftPresence-2.7.0+1.21.1-neoforge.DFqQfIBR.jar"
hash = "a5810b430aab2117f2b159cb14b6fb46fae38f73ab7050547516fcc3834e903b"

[[files]]
file = "mods/CreativeCore_NEOFORGE_v2.13.13_mc1.21.1.jar"
hash = "4ed0fc2d7b41f6bdca6c7e69eced4eea6cc6d82ee4c86cf549327ebb4429460c"

[[files]]
file = "mods/DistantHorizons-2.3.6-b-1.21.1-fabric-neoforge.jar"
hash = "542116269d76d7ad55c15444981ded68a8b186a2c677c5656446aa58422beffb"

[[files]]
file = "mods/ImmediatelyFast-NeoForge-1.6.7+1.21.1.5ZwdcRci.jar"
hash = "1998d56edb0ddb6caeedd09dd2fde405ee85cd8f706398cb8e08009fe9019058"

[[files]]
file = "mods/Jade-1.21.1-NeoForge-15.10.3.jar"
hash = "7087a9672a208071e774571423793d499a56adc8dd09fabe36f8652a3bb9c418"

[[files]]
file = "mods/JustEnoughResources-NeoForge-1.21.1-1.6.0.17.uEfK2CXF.jar"
hash = "7a47d69b5530704690d5a5f0726cd74a2d6c57df17dd4a8589c4ab5212f91460"

[[files]]
file = "mods/Ksyxis-1.3.4.jar"
hash = "7457f96dc1ef9f9c78307dba345e01ab8b8a0518a39fbb71d96e30abba888f0b"

[[files]]
file = "mods/LittleFrames_NEOFORGE_v1.4.6_mc1.21.1 (1).jar"
hash = "c8a24734a038eb36982de2819c21a5b446ee13bae4b10ca3e39d26faf3c0e084"

[[files]]
file = "mods/Resourcify (1.21.1-neoforge)-1.7.4.RLzHAoZe.jar"
hash = "da166f021e1d3a30735ddee58e066891a272d39bed005507f9c99f2b089b193f"

[[files]]
file = "mods/UniLib-1.2.0+1.21.1-neoforge.jar"
hash = "222c72818cf71c78416ee729d07645be287e9c5ee3058aa9913350a99b35a4ea"

[[files]]
file = "mods/alternate_current-mc1.21-1.9.0.jar"
hash = "d23731fcb31cf561544fd7a97b0076b3abb42a0ece0631f86de9a1425fe046f5"

[[files]]
file = "mods/appleskin-neoforge-mc1.21-3.0.7.EsAfCjCV.jar"
hash = "99a2f1b22f05b1215c6c967c0cf0518a39d30e18a94ac3dac248385e38dcfe10"

[[files]]
file = "mods/architectury-13.0.8-neoforge.jar"
hash = "5ec578f814e8cca87aeffa6e424032e78d9ea5ea6b603dd834c2dc13c31141ee"

[[files]]
file = "mods/bellsandwhistles-0.4.7-1.21.1.gJ5afkVv.jar"
hash = "a438cf2ea3a05120e12342484f1e12ca11526fbf4195d259ce1d7df8a9b3ffca"

[[files]]
file = "mods/bigcontraptions-neoforge-1.0.jv0UKGOX.jar"
hash = "7ed381abb65639833e8ddb708124c60387823cf3db95bdadc5fceb1b5c37fec8"

[[files]]
file = "mods/c2me-neoforge-mc1.21.1-0.3.0+alpha.0.87.jar"
hash = "d2d8fbc94f47f57ba9984a7a71fbef7c6f942a1061189ec60b7dc3411701e80d"

[[files]]
file = "mods/carryon-neoforge-1.21.1-2.2.2.11.jar"
hash = "b18c734fb574c05c78dd33c4cd4c152e55efc8aecc0b6de876cc21be3c147f7f"

[[files]]
file = "mods/copycats-3.0.2+mc.1.21.1-neoforge.UT2M39wf.jar"
hash = "8caf0e53cf250e1cc2811d49e9ea46f3c691f65c3522b55c19e24a411d1354ef"

[[files]]
file = "mods/coroutil-neoforge-1.21.0-1.3.8.jar"
hash = "9b32bcf2c793d33b93b5d4739c0dc4b64231025c7dc5fe40732b66d7cf4b2826"

[[files]]
file = "mods/create-1.21.1-6.0.6.jar"
hash = "2d403500cd550db452a975ec3d4ba21b6097360d4dd575311112fe322055b1ee"

[[files]]
file = "mods/create-dyn-light-forge-1.21.1-2.0.1.jar"
hash = "e2cb38a04c9808b559b7aeb0b21af9d50e86a40f9cf5f8a0975260e11d2b45d1"

[[files]]
file = "mods/create-track-map-2.0+mc1.21.1-neoforge.jar"
hash = "9c6894856b3b57373f76a08083d80d658e179b80b0f535459ea1e2f377c0694f"

[[files]]
file = "mods/createcontraptionterminals-1.21-1.2.0.gOPAFzp0.jar"
hash = "230b8c4876569767e0b794669c1a09ba7d25fa03710d0a06be5c671d80751326"

[[files]]
file = "mods/creategoggles-1.21.1-6.1.1-[NEOFORGE].L1RT5SJc.jar"
hash = "f08ff14c72ff15de9b3c87200ad06115ff48c73ac21458e038d6e137e162a907"

[[files]]
file = "mods/createrailwaysnavigator-neoforge-1.21.1-beta-0.8.4.jar"
hash = "77fc42a4084cae2d5ba950d45f9805de2bc3ceeff9776679fa61813e48121ab3"

[[files]]
file = "mods/curtain-mc1.21-1.3.2+build.314.jar"
hash = "51631275e116a9e3cbe695d4a7da1ead14954a4f4302daf4a207404f6e745a19"

[[files]]
file = "mods/drippyloadingscreen_neoforge_3.0.12_MC_1.21.1.jar"
hash = "a0d941bda35becbfbeaef02590cc2dd64228fa497a302292156192c2ee1e5c1e"

[[files]]
file = "mods/dynamic-fps-3.9.5+minecraft-1.21.0-neoforge.LQ3K71Q1.jar"
hash = "269ea911c14ba63c972b85f43ff4da1c940faae4e80a496d6416a5f683d1b7c2"

[[files]]
file = "mods/enhancedgroups-neoforge-1.21.1-1.21.1-1.7.0.jar"
hash = "6413469e14816ab5f9447787ada2db7491ae728820241dda5dbf6c4a8c621ee1"

[[files]]
file = "mods/entityculling-neoforge-1.9.3-mc1.21.1.NNAgCjsB.jar"
hash = "d79464477f7f845091387529bf0c1e565d62551cdb1adb2a16dcf8c9d22bf200"

[[files]]
file = "mods/exposure-neoforge-1.21.1-1.9.11.jar"
hash = "35339f608762d0c886d2cb9a21f6eb8ca9d56ff9a9701cc4bf9c6f8000bba20e"

[[files]]
file = "mods/exposure_polaroid-neoforge-1.21.1-1.1.2.WEWiqYkW.jar"
hash = "3b8b50e27a8985f94e5208a2c68f503f5d504c50e4bf753c421ea91a92f372ca"

[[files]]
file = "mods/fancy-entity-renderer-neoforge-1.21-0.4.1.jar"
hash = "b9d5d4abf8091acabebce2a48f0d1af85b7ece543d8b6f903f83474f92f27b00"

[[files]]
file = "mods/fancymenu_neoforge_3.7.0_MC_1.21.1.jar"
hash = "3c6cce7ef18254c13e2e061cb882160c9d00f91b09bb589423baccc4f4366462"

[[files]]
file = "mods/ferritecore-7.0.2-neoforge.uXXizFIs.jar"
hash = "235e2081dfe050d7642b0d432a786668f079168505ba5d6bf0ec70c962a36539"

[[files]]
file = "mods/forgified-fabric-api-0.115.6+2.1.4+1.21.1.Aqlf1Shp.jar"
hash = "c98b7d44a64348311b9be1a6a5565c0027590dbdb08a21817cb2347393b14c4e"

[[files]]
file = "mods/fusion-1.2.11b-neoforge-mc1.21.jar"
hash = "626340f7a4ff1cf406d73da3d7e328c17818e8f41b983912333da47287143b56"

[[files]]
file = "mods/immersive_optimization-neoforge-1.21-0.1.0.jar"
hash = "7ce5d8b5257b178d53a8da30bdb5b1bc297c031ba3545356ee64d041f5e46522"

[[files]]
file = "mods/iris-flywheel-compat-NeoForge-2.0.5.jar"
hash = "9271d36c52f4dd1759e4bdd80fb61f5bdf8abfbd16f43cc22761a67d25cd83e7"

[[files]]
file = "mods/iris-neoforge-1.8.12+mc1.21.1.jar"
hash = "3e3f94d2d5cdcb8145c4385d521974aa2d8669b2cc212351f70cf06488182e83"

[[files]]
file = "mods/jei-1.21.1-neoforge-19.25.0.323.u6dRKJwZ.jar"
hash = "a46baba7b85d465503e7cf382533b96af845a8ab37748637360a441d0ef2030d"

[[files]]
file = "mods/journeymap-neoforge-1.21.1-6.0.0-beta.52.lfHFW1mp.jar"
hash = "1eb931a3b0e333c537be14231eee3ec67d262bc338ba6ecc36922690142c37a2"

[[files]]
file = "mods/konkrete_neoforge_1.9.9_MC_1.21.jar"
hash = "791c5538751dd3015ef3a2ce92d98719e1a28a48ebbd817b78506771256654cd"

[[files]]
file = "mods/kotlinforforge-5.10.0-all.jar"
hash = "3f6e1d0e34c86e62abce3a9f86764a6861a2101aaa8858ada9d81f4588336efe"

[[files]]
file = "mods/lambdynamiclights-4.8.7+1.21.1.jar"
hash = "30ce0c25f703d1a53540359447f11d35b411f5c75481555b0dc45ffa8d62006b"

[[files]]
file = "mods/lithium-neoforge-0.15.0+mc1.21.1.jar"
hash = "8b671fa5486487c03d13543560a4909bc57c8933e200f62a7d79947aa48a8e41"

[[files]]
file = "mods/mc-world-export-0.9.3.jar"
hash = "5f43d57ae6199d1f2edb90bf44f3e542fc64a237d3cbd61e767dec59dbc1b700"

[[files]]
file = "mods/mcef-neoforge-2.1.6-1.21.1.jar"
hash = "0c7696216fa5cfee659d687475873c847a9a17cc8ce3a56119a69c946eeb8772"

[[files]]
file = "mods/melody_neoforge_1.0.10_MC_1.21.jar"
hash = "6b973a4564703c531fc0eae09db08b07a38091e0a743c687b8d2049457e84871"

[[files]]
file = "mods/modernfix-neoforge-5.25.1+mc1.21.1.jar"
hash = "2dbcf6cd837fca938323dd55114e6c515a4bb1b644a746aad504dd8d43bb0b6d"

[[files]]
file = "mods/modflared-1.2.2+release.81.jar"
hash = "abf1b1262f0b888fa6c864efd8e5a084149753e815bc7112edaa6f26b1b45466"

[[files]]
file = "mods/no-telemetry-1.9.0.hg77g4Pw.jar"
hash = "2736522c5fec19471c54a665242eb4c314f35483b987c7a7c44fe1354a04542e"

[[files]]
file = "mods/notenoughanimations-neoforge-1.10.6-mc1.21.1.MPCX6s5C.jar"
hash = "a1d50a33e0efe740b75ffd574cc2d81992bb8c3c421cd324edf15bc24bf02e01"

[[files]]
file = "mods/packetfixer-3.3.0-1.20.5-1.21.X-merged.jar"
hash = "3285a55983d9c02b82d5707ab1e1fe942a81a5b7ea8c845e753ecdcd4ed5b1ab"

[[files]]
file = "mods/polymorph-neoforge-1.1.0+1.21.1.tagwiZkJ.jar"
hash = "bec8118978adeb052de9c4eaf9a595830621d82515a764f32f9c8a4dd52ab94b"

[[files]]
file = "mods/rechiseled-1.1.6a-neoforge-mc1.21.B0g2vT6l.jar"
hash = "7e64fa40a2c54fd139d1a02b121260cf3c543638924ac09e25dd5b795fc1ccb4"

[[files]]
file = "mods/rechiseledcreate-1.0.2a-neoforge-mc1.21.E6867niZ.jar"
hash = "a9bb3a70c3a7356b1cde0ad598927ad22992b54b4e7b05f2cedb4f2c17cb2381"

[[files]]
file = "mods/reforgedplaymod-1.21.1-0.3.jar"
hash = "608481672d6afbd0926427e58dcbfb1c66421d9364aa00e67696bcdc9c5f5cc0"

[[files]]
file = "mods/saturn-mc1.21.1-0.1.5.jar"
hash = "f49f4b51faeb4e9eb7568723fa259c0da1c3460f8019597f04a54c2137b76c32"

[[files]]
file = "mods/scholar-neoforge-1.21.1-1.1.9.fX4dIQCo.jar"
hash = "96ce2c68132d24398c21d5285da62ae7e3f63a01421def39d136e2f0fbf80ee1"

[[files]]
file = "mods/servercore-neoforge-1.5.5+1.21.1.jar"
hash = "528b60a3531819e6d5d4c98d8f858c39467b9234d2b5f20c31b48562073b67b0"

[[files]]
file = "mods/skinlayers3d-neoforge-1.9.2-mc1.21.1.zV5r3pPn.jar"
hash = "d6864ecc8e7a169fcecbcdbaab024ff3b364f093abbedb041afe8515ee5628b8"

[[files]]
file = "mods/sodium-neoforge-0.6.13+mc1.21.1.jar"
hash = "7acd7af2ef75ec883a6872c17494ead65e38025151eb08a1d60e36d34377f403"

[[files]]
file = "mods/sodiumdynamiclights-neoforge-1.0.10-1.21.1.PxQSWIcD.jar"
hash = "d78002d50865db928fbf2c17c716ffcbbd6d33bff88aa1f0f3a04152a2665e25"

[[files]]
file = "mods/sootychimneys-neoforge-1.3.3.b3w1XM9H.jar"
hash = "31ce578443c84bd1bf1f5748f9eeac7cd1c35e242932de8959dfb8aaff6224f3"

[[files]]
file = "mods/supermartijn642configlib-1.1.8-neoforge-mc1.21.jar"
hash = "d2ba7b839a2268e4e223457e813d11aa2476c3bf708a7bba691d8fc851778a4b"

[[files]]
file = "mods/supermartijn642corelib-1.1.18a-neoforge-mc1.21.jar"
hash = "6f43f2fa77968569927edefde859f1c46d7317c5519cdcefea729e9b84342420"

[[files]]
file = "mods/toms_storage-1.21-2.2.2.jar"
hash = "56c0d14e3701d24b9e2bb6d96bf6870d6193157214f70186c896f925542024bf"

[[files]]
file = "mods/voicechat-neoforge-1.21.1-2.6.6.jar"
hash = "d6b030f5e217d904aaca29c6e6f1a6b7365be6931db0bd7632e6385805b498b1"

[[files]]
file = "mods/watermedia-2.1.36.jar"
hash = "9f2b54c4d5c9d680ee8a50e0bed1d982d0667d3ee7097765effcae6b2478d690"

[[files]]
file = "mods/watut-neoforge-1.21.0-1.2.7.AtB5mHky.jar"
hash = "b1aac4b9832e16439ee86f27814f7b6a42f2f6bea0ea6949dfffffcd0599d88c"

[[files]]
file = "mods/worldedit-mod-7.3.8.1u6JkXh5.jar"
hash = "5e7752c97876d87411e3760bcc573cc431f43c453722e6959fa7fe54db1b01ca"
