name = "Modpack Complicatedcraft"
author = "PGSCOM"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "542606166f93a12fe14582a74544417ed7cef840f35dde46e7e614b5caa27873"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.192"
