name = "Modpack Complicatedcraft"
author = "PGSCOM"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a4bbd68318ef58010304cc3fca0afa2ac13dcf7e913feff1dc05dcdeec700741"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.192"
