name = "Modpack Complicatedcraft"
author = "PGSCOM"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e7eeba993a1a87fad96a30173b36cf92fe7fce2abc58858de166ad489872e110"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.192"
